Added Scene path inference for LoadSceneAttribute & BuildSceneAttribute
nowsprinting/test-helper pull request #94
Opened 2024-08-20 21:08 UTC by faviann

Enhanced flexibility of LoadSceneAttribute & BuildSceneAttribute by allowing scene paths to be also fully inferred from the CallerFilePath. 

Should the value path be omitted/null/empty from the attribute, the scene path will be derived from the test file name.
 /// (e.g., `Asset/Tests/ScreenshotTest.cs` will load `./ScreenshotTest.unity`)

I was not sure if you would've preferred this to be implemented differently but I made a pull request with this feature in case this is something you would see as useful for others. Please feel free to request some changes (or just refuse).

2024-08-23 02:24 UTC, nowsprinting requested changes
Thanks, It is a great idea!

I have written a few minor comments.
Please fix them.

2024-08-23 02:24 UTC, nowsprinting commented on Runtime/Attributes/BuildSceneAttribute.cs
> +using UnityEditor;
unnecessary?

2024-08-23 02:24 UTC, nowsprinting commented on Runtime/Attributes/BuildSceneAttribute.cs
> +        /// - For the process of including a Scene not in "Scenes in Build" to a build for player, see: <see cref="Editor.TemporaryBuildScenesUsingInTest"/>.
unnecessary change?

2024-08-23 02:24 UTC, nowsprinting commented on Tests/Runtime/Attributes/BuildSceneAttributeInferredTest.cs
> +        private const string ObjectName = "CubeInNotInScenesInBuild";
Please give it a name different from the GameObject name used in the existing BuildSceneAttributeTest.
The test will fail when run consecutively.

2024-08-23 02:24 UTC, nowsprinting commented on Tests/Runtime/Attributes/BuildSceneAttributeInferredTest.cs
> +    public class BuildSceneAttributeInferredTest
Please add a method to the BuildSceneAttributeTest class. (Do not create this class.)
BuildSceneAttributes can be multiple specified.

2024-08-23 08:47 UTC, nowsprinting commented
@faviann san, please rebase onto v0.7.3

2024-08-27 00:29 UTC, faviann commented on Runtime/Attributes/BuildSceneAttribute.cs
> +using UnityEditor;
Agreed, I wrongly committed this

2024-08-27 00:29 UTC, faviann commented on Runtime/Attributes/BuildSceneAttribute.cs
> +        /// - For the process of including a Scene not in "Scenes in Build" to a build for player, see: <see cref="Editor.TemporaryBuildScenesUsingInTest"/>.
Agreed, I also wrongly committed this

2024-08-27 00:34 UTC, faviann commented
I rebased on the most recent master branch. If there is anything else needed you feel free to request additional changes. 

I will also be more careful to not let silly errors slip by.

2024-08-27 23:21 UTC, nowsprinting approved these changes
Thank you!

2024-08-27 23:21 UTC, merged